# Generated by Django 4.2.30 on 2026-05-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creada'),
        ),
        migrations.AddField(
            model_name='cita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Actualizada'),
        ),
    ]
